name: Claude PR Review with Custom Gitea URL
on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    steps:
      - name: Claude Code Analysis
        uses: markwylde/claude-code-gitea-action@gitea
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}
        env:
          # Set this to your public Gitea URL to override the internal container URL
          # This ensures that links in comments point to the correct public URL
          GITEA_SERVER_URL: https://gitea.example.com
          
          # Note: GITHUB_SERVER_URL is automatically set by Gitea Actions to the internal URL
          # but it will be overridden by GITEA_SERVER_URL if set above
